name: Build & Deploy MyKas (PWA Web & Android APK)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Tarik Code Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter (3.24.3)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      # 1. Generate Folder Android & Timpa MainActivity.kt dengan FlutterFragmentActivity
      - name: Generate Android Project & Fix FragmentActivity
        run: |
          flutter create . --platforms=android --org com.mykas.app --project-name mykas
          mkdir -p android/app/src/main/kotlin/com/mykas/app/mykas
          cat << 'EOF' > android/app/src/main/kotlin/com/mykas/app/mykas/MainActivity.kt
          package com.mykas.app.mykas

          import io.flutter.embedding.android.FlutterFragmentActivity

          class MainActivity: FlutterFragmentActivity() {
          }
          EOF

      # 2. Build Flutter Web PWA
      - name: Build Flutter Web
        run: flutter build web --release --base-href "/MyKas/" --no-tree-shake-icons

      # 3. Build APK Android Release
      - name: Build Android APK
        run: flutter build apk --release

      # 4. Upload Web Artifact untuk GitHub Pages
      - name: Upload Web Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      # 5. Upload File APK ke GitHub Artifacts
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyKas-Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk

  deploy-web:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
